services:
  database:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: saldop_api
      POSTGRES_PASSWORD: saldop_api_password
      POSTGRES_DB: saldop
    ports:
      - "54329:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saldop_api"]
      interval: 10s
      retries: 5
      timeout: 5s

  test_database:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_db"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  database_data:
