// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"pt_BR": &dictionary{index: pt_BRIndex, data: pt_BRData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"must be provided":                     0,
	"should be at least 3 characters long": 1,
	"should be at least 8 characters long": 2,
}

var en_USIndex = []uint32{ // 4 elements
	0x00000000, 0x00000011, 0x00000036, 0x0000005b,
} // Size: 40 bytes

const en_USData string = "" + // Size: 91 bytes
	"\x02must be provided\x02should be at least 3 characters long\x02should b" +
	"e at least 8 characters long"

var pt_BRIndex = []uint32{ // 4 elements
	0x00000000, 0x00000016, 0x00000036, 0x00000056,
} // Size: 40 bytes

const pt_BRData string = "" + // Size: 86 bytes
	"\x02precisa ser informado\x02deve ter pelomenos 3 caracteres\x02deve ter" +
	" pelomenos 8 caracteres"

	// Total table size 257 bytes (0KiB); checksum: FBB5ABB6
