// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"pt_BR": &dictionary{index: pt_BRIndex, data: pt_BRData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"cannot be empty":                      4,
	"cannot be greater than 200":           1,
	"must be an integer value":             2,
	"must be provided":                     3,
	"should be 26 bytes long":              6,
	"should be at least 3 characters long": 7,
	"should be at least 8 characters long": 5,
	"should be greater than zero":          0,
}

var en_USIndex = []uint32{ // 9 elements
	0x00000000, 0x0000001c, 0x00000037, 0x00000050,
	0x00000061, 0x00000071, 0x00000096, 0x000000ae,
	0x000000d3,
} // Size: 60 bytes

const en_USData string = "" + // Size: 211 bytes
	"\x02should be greater than zero\x02cannot be greater than 200\x02must be" +
	" an integer value\x02must be provided\x02cannot be empty\x02should be at" +
	" least 8 characters long\x02should be 26 bytes long\x02should be at leas" +
	"t 3 characters long"

var pt_BRIndex = []uint32{ // 9 elements
	0x00000000, 0x00000018, 0x00000034, 0x0000004b,
	0x00000061, 0x00000077, 0x00000097, 0x000000c1,
	0x000000e1,
} // Size: 60 bytes

const pt_BRData string = "" + // Size: 225 bytes
	"\x02deve ser maior que zero\x02não pode ser maior que 200\x02precisa ser" +
	" um inteiro\x02precisa ser informado\x02não pode estar vazio\x02deve ter" +
	" pelomenos 8 caracteres\x02deveria ter pelomenos 26 bytes de tamanho\x02" +
	"deve ter pelomenos 3 caracteres"

	// Total table size 556 bytes (0KiB); checksum: D10831F4
