// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"pt_BR": &dictionary{index: pt_BRIndex, data: pt_BRData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"cannot be empty":                      1,
	"must be provided":                     0,
	"should be 26 bytes long":              3,
	"should be at least 3 characters long": 4,
	"should be at least 8 characters long": 2,
}

var en_USIndex = []uint32{ // 6 elements
	0x00000000, 0x00000011, 0x00000021, 0x00000046,
	0x0000005e, 0x00000083,
} // Size: 48 bytes

const en_USData string = "" + // Size: 131 bytes
	"\x02must be provided\x02cannot be empty\x02should be at least 8 characte" +
	"rs long\x02should be 26 bytes long\x02should be at least 3 characters lo" +
	"ng"

var pt_BRIndex = []uint32{ // 6 elements
	0x00000000, 0x00000016, 0x0000002c, 0x0000004c,
	0x00000076, 0x00000096,
} // Size: 48 bytes

const pt_BRData string = "" + // Size: 150 bytes
	"\x02precisa ser informado\x02não pode estar vazio\x02deve ter pelomenos " +
	"8 caracteres\x02deveria ter pelomenos 26 bytes de tamanho\x02deve ter pe" +
	"lomenos 3 caracteres"

	// Total table size 377 bytes (0KiB); checksum: EB8914E9
