// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"pt_BR": &dictionary{index: pt_BRIndex, data: pt_BRData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"can only be BANK or CREDIT":           4,
	"cannot be empty":                      5,
	"cannot be greater than 200":           2,
	"must be an integer value":             0,
	"must be provided":                     3,
	"should be 26 bytes long":              7,
	"should be at least 3 characters long": 8,
	"should be at least 8 characters long": 6,
	"should be greater than zero":          1,
}

var en_USIndex = []uint32{ // 10 elements
	0x00000000, 0x00000019, 0x00000035, 0x00000050,
	0x00000061, 0x0000007c, 0x0000008c, 0x000000b1,
	0x000000c9, 0x000000ee,
} // Size: 64 bytes

const en_USData string = "" + // Size: 238 bytes
	"\x02must be an integer value\x02should be greater than zero\x02cannot be" +
	" greater than 200\x02must be provided\x02can only be BANK or CREDIT\x02c" +
	"annot be empty\x02should be at least 8 characters long\x02should be 26 b" +
	"ytes long\x02should be at least 3 characters long"

var pt_BRIndex = []uint32{ // 10 elements
	0x00000000, 0x00000017, 0x0000002f, 0x0000004b,
	0x00000061, 0x00000080, 0x00000096, 0x000000b6,
	0x000000e0, 0x00000100,
} // Size: 64 bytes

const pt_BRData string = "" + // Size: 256 bytes
	"\x02precisa ser um inteiro\x02deve ser maior que zero\x02não pode ser ma" +
	"ior que 200\x02precisa ser informado\x02pode ser apenas BANK ou CREDIT" +
	"\x02não pode estar vazio\x02deve ter pelomenos 8 caracteres\x02deveria t" +
	"er pelomenos 26 bytes de tamanho\x02deve ter pelomenos 3 caracteres"

	// Total table size 622 bytes (0KiB); checksum: BE2717FA
